spring.application.name=Pokemon Draft League Portal
spring.datasource.url=${DATABASE_URL:jdbc:h2:file:./data/leagueportal}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
server.port=${PORT:8080}
server.servlet.session.timeout=12h
