package com.pokemondraft.leagueportal.service;

import com.pokemondraft.leagueportal.model.*;
import com.pokemondraft.leagueportal.repository.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;

@Service
public class FreeAgencyService {
    private static final int ROSTER_LIMIT=10, ROSTER_BUDGET=100;
    private final FreeAgentBidRepository bids; private final TeamRepository teams; private final PokemonRepository pokemon;
    private final RosterEntryRepository roster; private final TransactionRecordRepository transactions; private final TradeOfferRepository trades;
    public FreeAgencyService(FreeAgentBidRepository bids,TeamRepository teams,PokemonRepository pokemon,RosterEntryRepository roster,TransactionRecordRepository transactions,TradeOfferRepository trades){this.bids=bids;this.teams=teams;this.pokemon=pokemon;this.roster=roster;this.transactions=transactions;this.trades=trades;}

    public FreeAgentBid submitBid(Long teamId,Long wanted,Long drop,int amount){Team t=teams.findById(teamId).orElseThrow();if(t.getFaBudget()<=0)throw bad("You have no FAAB remaining");if(amount<=0||amount>t.getFaBudget())throw bad("Bid must be between $1 and your remaining FAAB");if(wanted==null)throw bad("Choose a free agent");Pokemon w=pokemon.findById(wanted).orElseThrow(()->bad("Free agent does not exist"));if(roster.findByPokemonId(wanted).isPresent()||w.isDrafted())throw new ResponseStatusException(HttpStatus.CONFLICT,"Wanted Pokemon is not a free agent");int count=(int)roster.countByTeamId(teamId);if(count>=ROSTER_LIMIT&&drop==null)throw bad("Your roster is full. Choose one Pokemon to drop if this bid wins");int value=rosterValue(teamId)+w.getPrice();if(drop!=null){RosterEntry d=verifyOwner(teamId,drop);Pokemon dp=pokemon.findById(d.getPokemonId()).orElseThrow();value-=dp.getPrice();}if(value>ROSTER_BUDGET)throw bad("Move would put roster value at $"+value+"/$100");return bids.save(new FreeAgentBid(teamId,wanted,drop,amount));}
    @Transactional public int processBids(){List<FreeAgentBid> pending=bids.findByStatus(BidStatus.PENDING);Map<Long,List<FreeAgentBid>> groups=new LinkedHashMap<>();for(FreeAgentBid b:pending)groups.computeIfAbsent(b.getWantedPokemonId(),k->new ArrayList<>()).add(b);int winners=0;for(List<FreeAgentBid> g:groups.values()){g.sort(Comparator.comparingInt(FreeAgentBid::getAmount).reversed().thenComparing(FreeAgentBid::getCreatedAt));FreeAgentBid winner=null;for(FreeAgentBid b:g)if(canApplyBid(b)){winner=b;break;}for(FreeAgentBid b:g)b.setStatus(b==winner?BidStatus.WON:BidStatus.LOST);if(winner!=null){applyWinningBid(winner);winners++;}bids.saveAll(g);}return winners;}
    private boolean canApplyBid(FreeAgentBid b){Team t=teams.findById(b.getTeamId()).orElse(null);Pokemon w=pokemon.findById(b.getWantedPokemonId()).orElse(null);if(t==null||w==null||b.getAmount()<=0||b.getAmount()>t.getFaBudget()||roster.findByPokemonId(b.getWantedPokemonId()).isPresent()||w.isDrafted())return false;int count=(int)roster.countByTeamId(b.getTeamId());if(b.getDropPokemonId()==null)return count<ROSTER_LIMIT&&rosterValue(b.getTeamId())+w.getPrice()<=ROSTER_BUDGET;Optional<RosterEntry>d=roster.findByPokemonId(b.getDropPokemonId());if(d.isEmpty()||!d.get().getTeamId().equals(b.getTeamId()))return false;Pokemon dp=pokemon.findById(b.getDropPokemonId()).orElse(null);return dp!=null&&rosterValue(b.getTeamId())-dp.getPrice()+w.getPrice()<=ROSTER_BUDGET;}
    private void applyWinningBid(FreeAgentBid b){Team t=teams.findById(b.getTeamId()).orElseThrow();Pokemon w=pokemon.findById(b.getWantedPokemonId()).orElseThrow();String dropText="";int value;if(b.getDropPokemonId()!=null){Pokemon dp=pokemon.findById(b.getDropPokemonId()).orElseThrow();RosterEntry de=verifyOwner(t.getId(),dp.getId());value=rosterValue(t.getId())-dp.getPrice()+w.getPrice();roster.delete(de);dp.setDrafted(false);pokemon.save(dp);dropText=" and dropped "+dp.getName();}else value=rosterValue(t.getId())+w.getPrice();if(value>ROSTER_BUDGET)throw bad("Winning bid exceeds $100 roster budget");roster.save(new RosterEntry(t.getId(),w.getId()));w.setDrafted(true);pokemon.save(w);t.setFaBudget(t.getFaBudget()-b.getAmount());teams.save(t);transactions.save(new TransactionRecord("FREE_AGENCY",t.getName()+" added "+w.getName()+" for $"+b.getAmount()+" FAAB"+dropText+". Roster value: $"+value+"/$100; FAAB remaining: $"+t.getFaBudget()));cancelImpossibleTrades(Set.of(w.getId()));}

    public TradeOffer offerTrade(Long teamId,Long recipient,List<Long> offered,List<Long> requested,int proposerFaab,int recipientFaab){
        if(recipient==null)throw bad("Choose a team");if(teamId.equals(recipient))throw bad("Cannot trade with yourself");
        offered=clean(offered);requested=clean(requested);if(offered.isEmpty()&&requested.isEmpty()&&proposerFaab==0&&recipientFaab==0)throw bad("Trade must include Pokemon or FAAB");if(proposerFaab<0||recipientFaab<0)throw bad("FAAB cannot be negative");
        Team p=teams.findById(teamId).orElseThrow(),r=teams.findById(recipient).orElseThrow();if(proposerFaab>p.getFaBudget()||recipientFaab>r.getFaBudget())throw bad("Trade includes more FAAB than a team owns");
        for(Long id:offered)verifyOwner(teamId,id);for(Long id:requested)verifyOwner(recipient,id);validateTrade(teamId,recipient,offered,requested);return trades.save(new TradeOffer(teamId,recipient,offered,requested,proposerFaab,recipientFaab));
    }
    public TradeOffer offerTrade(Long teamId,Long recipient,Long offered,Long requested,int pf,int rf){return offerTrade(teamId,recipient,offered==null?List.of():List.of(offered),requested==null?List.of():List.of(requested),pf,rf);}
    public TradeOffer offerTrade(Long teamId,Long recipient,Long offered,Long requested){return offerTrade(teamId,recipient,offered,requested,0,0);}

    @Transactional public TradeOffer respondTrade(Long id,Long actingTeamId,boolean manager,boolean accept){
        TradeOffer tr=trades.findById(id).orElseThrow();if(tr.getStatus()!=TradeStatus.PENDING)throw bad("Trade already resolved");if(!manager&&!tr.getRecipientTeamId().equals(actingTeamId))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Only recipient can respond");if(!accept){tr.setStatus(TradeStatus.REJECTED);return trades.save(tr);}
        List<Long> offered=tr.getOfferedPokemonIds(),requested=tr.getRequestedPokemonIds();for(Long x:offered)verifyOwner(tr.getProposerTeamId(),x);for(Long x:requested)verifyOwner(tr.getRecipientTeamId(),x);int[] values=validateTrade(tr.getProposerTeamId(),tr.getRecipientTeamId(),offered,requested);
        Team p=teams.findById(tr.getProposerTeamId()).orElseThrow(),r=teams.findById(tr.getRecipientTeamId()).orElseThrow();if(tr.getProposerFaab()>p.getFaBudget()||tr.getRecipientFaab()>r.getFaBudget()){tr.setStatus(TradeStatus.CANCELLED);trades.save(tr);throw bad("Trade closed because a team no longer has the included FAAB");}
        for(Long x:offered){RosterEntry e=verifyOwner(p.getId(),x);e.setTeamId(r.getId());roster.save(e);}for(Long x:requested){RosterEntry e=verifyOwner(r.getId(),x);e.setTeamId(p.getId());roster.save(e);}
        p.setFaBudget(p.getFaBudget()-tr.getProposerFaab()+tr.getRecipientFaab());r.setFaBudget(r.getFaBudget()-tr.getRecipientFaab()+tr.getProposerFaab());teams.save(p);teams.save(r);tr.setStatus(TradeStatus.ACCEPTED);trades.save(tr);
        Set<Long> moved=new HashSet<>(offered);moved.addAll(requested);cancelImpossibleTradesExcept(moved,tr.getId());
        String desc=p.getName()+" traded "+describe(offered,tr.getProposerFaab())+" to "+r.getName()+" for "+describe(requested,tr.getRecipientFaab());transactions.save(new TransactionRecord("TRADE",desc+". Roster values: $"+values[0]+"/$100 and $"+values[1]+"/$100. FAAB remaining: $"+p.getFaBudget()+" / $"+r.getFaBudget()));return tr;
    }
    private int[] validateTrade(Long p,Long r,List<Long> offered,List<Long> requested){int pc=(int)roster.countByTeamId(p)-offered.size()+requested.size(),rc=(int)roster.countByTeamId(r)-requested.size()+offered.size();if(pc>ROSTER_LIMIT||rc>ROSTER_LIMIT)throw bad("Trade would put a team over 10 Pokemon");int pv=rosterValue(p)-value(offered)+value(requested),rv=rosterValue(r)-value(requested)+value(offered);if(pv>ROSTER_BUDGET||rv>ROSTER_BUDGET)throw bad("Trade would exceed the $100 roster budget");return new int[]{pv,rv};}
    @Transactional public void cancelImpossibleTrades(Set<Long> moved){cancelImpossibleTradesExcept(moved,null);}
    private void cancelImpossibleTradesExcept(Set<Long> moved,Long acceptedId){for(TradeOffer t:trades.findAll()){if(t.getStatus()!=TradeStatus.PENDING||Objects.equals(t.getId(),acceptedId))continue;boolean conflict=t.getOfferedPokemonIds().stream().anyMatch(moved::contains)||t.getRequestedPokemonIds().stream().anyMatch(moved::contains);if(conflict){t.setStatus(TradeStatus.CANCELLED);trades.save(t);}}}
    private List<Long> clean(List<Long> ids){return ids==null?List.of():ids.stream().filter(Objects::nonNull).distinct().toList();}
    private int value(List<Long> ids){int v=0;for(Long id:ids)v+=pokemon.findById(id).map(Pokemon::getPrice).orElse(0);return v;}
    private String describe(List<Long> ids,int faab){List<String> parts=new ArrayList<>();for(Long id:ids)parts.add(pokemon.findById(id).map(Pokemon::getName).orElse("Pokemon"));if(faab>0)parts.add("$"+faab+" FAAB");return parts.isEmpty()?"nothing":String.join(" + ",parts);}
    private int rosterValue(Long teamId){int n=0;for(RosterEntry e:roster.findByTeamId(teamId))n+=pokemon.findById(e.getPokemonId()).map(Pokemon::getPrice).orElse(0);return n;}
    private RosterEntry verifyOwner(Long teamId,Long pokemonId){RosterEntry e=roster.findByPokemonId(pokemonId).orElseThrow(()->bad("Pokemon is not rostered"));if(!e.getTeamId().equals(teamId))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Pokemon belongs to another team");return e;}
    private ResponseStatusException bad(String s){return new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}
}
